### ISSUE TITLE
Hide close button

### ISSUE THREAD

**Issue by levantu2003** [PonyLucky/gh0stzk-Firefox#2]
Do you have any idea for hide these one ?

![Screenshot_2023-05-21-15-58-49_1782](https://github.com/PonyLucky/gh0stzk-Firefox/assets/107534756/ca40aa5c-e988-4c60-93ff-48147cafaa0c)

**Comment by PonyLucky** [comment]
First, those button are dependent of the OS you're in (Windows I assume). I use PopOS! (based on Debian, a Linux distribution) and on the settings of my OS I can hide those I want. So it's possible that Firefox only places them and don't have (or let) access to them.

Still I'll dig into it.

**Comment by PonyLucky** [comment]
According to that post: https://www.reddit.com/r/FirefoxCSS/comments/y47bx3/how_to_remove_firefox_close_button_x_windows/

It's possible adding this to the end of `userChrome.css`:
```css
/*Hide app's close, minimize and maximize buttons*/
.titlebar-buttonbox-container{
  display: none !important;
}
```
